### ISSUE TITLE
Pokemon Emerald: The internal battery has run dry

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [Browncha023/GBA#24]
The internal battery has run dry.
The game can be played
However, clock-based events will no longer occur.
![image](https://user-images.githubusercontent.com/65097669/147009196-aa6ec542-ff6d-4da4-9194-d17e7d562289.png)
![image](https://user-images.githubusercontent.com/65097669/147009209-8370e9c3-7e54-4cb2-b237-88723ec604f0.png)
There are no errors in the console, and this has occurred on multiple of my devices (chromebook and pc), on multiple browsers (firefox and chrome). This also happens with Pokemon Ruby.
Potential solutions include different .gba files or using another emulator, such as GBA.js which is able to run these

**Comment by FoxNerdSaysMoo** [comment]
Using an alternate GBA file did not work (at least the one I tried)

**Comment by Browncha023** [comment]
This version of Iodine isn't meant to emulate the internal batteries the original gba cartridges had, the game works as normal though so it isn't an issue. If it bugs you, fork the project and spend a few weeks updating to an Iodine version that does emulate it.
