### ISSUE TITLE
Hi hello i myself have an issue with the Gba emulator

### ISSUE THREAD

**Issue by kingof985** [Browncha023/GBA#25]
How am i supposed to save my gba save files please respond as i like to play gba in my free time

**Comment by Browncha023** [comment]
You can either:
A. Download the cookie using a tool or by messing around with inspect in your browser.
B. Spend a few weeks updating a fork of the project to the latest version on Iodine [which supports save file downloading].
Or C. Use a newer version of walsh/jsemu and spend a while uploading the roms and setting the game variables.

>>> I don't plan to update the Iodine version anytime soon.
